export const cats = [
    {
        name: "Fish",
        gender: "Male",
        age: "Young",
        size: "Medium",
        color: "Tabby (Brown / White / Black)",
        characteristics: ["Friendly", "Adventerous", "Funny"],
        houseTrained: "Yes",
        health: "Spayed/Neutered, vaccinations up to date",
        goodWith: "Other cats, children.",
        adoptionFee: "$75.00",
        imageUrl: "images/cats/fish.webp",
        id: "0001"
    },
    {
        name: "King",
        gender: "Male",
        age: "Kitten",
        size: "Small",
        color: "Gray",
        characteristics: ["Shy", "Friendly", "Playful"],
        houseTrained: "No",
        health: "Spayed/Neutered, vaccinations up to date",
        goodWith: "Other cats, children, dogs.",
        adoptionFee: "$100.00",
        imageUrl: "images/cats/king.webp",
        id: "0002"
    },
    {
        name: "Maxwell",
        gender: "Female",
        age: "Adult",
        size: "Large",
        color: "Tabby (Brown / White / Black)",
        characteristics: ["Friendly", "Adventerous", "Funny"],
        houseTrained: "Yes",
        health: "Spayed/Neutered, vaccinations up to date",
        goodWith: "Other cats, dogs",
        adoptionFee: "$75.00",
        imageUrl: "images/cats/maxwell.webp",
        id: "0003"
    },
    {
        name: "Admiral Meowington",
        gender: "Male",
        age: "Senior",
        size: "Medium",
        color: "Hairless",
        characteristics: ["Quiet", "Brave", "Gentle"],
        houseTrained: "Yes",
        health: "Spayed/Neutered, vaccinations up to date",
        goodWith: "Children, other cats, children.",
        adoptionFee: "$50.00",
        imageUrl: "images/cats/admiralmeowington.webp",
        id: "0004"
    },
    {
        name: "Sir Pounce-A-Lot",
        gender: "Male",
        age: "Adult",
        size: "Large",
        color: "White / Gray",
        characteristics: ["Gentle", "Athletic", "Affectionate", "Friendly", "Curious", "Playful", "Athletic"],
        houseTrained: "Yes",
        health: "Spayed/Neutered, vaccinations up to date",
        goodWith: "Other cats.",
        adoptionFee: "$95.00",
        imageUrl: "images/cats/sirpouncealot.webp",
        id: "0005"
    },
    {
        name: "Tiddy",
        gender: "Female",
        age: "Adult",
        size: "Medium",
        color: "Black",
        characteristics: ["Affectionate", "Playful", "Friendly"],
        houseTrained: "Yes",
        health: "Spayed/Neutered",
        goodWith: "Other cats.",
        adoptionFee: "$95.00",
        imageUrl: "images/cats/tiddy.webp",
        id: "0006"
    },
    {
        name: "Nacho",
        gender: "Female",
        age: "Young",
        size: "Medium",
        color: "Tabby (Brown / White / Black)",
        characteristics: ["Friendly", "Affectionate", "Gentle", "Playful", "Smart", "Brave", "Curious", "Funny", "Athletic", "Loves Kisses", "Brave"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "Other cats.",
        adoptionFee: "$95.00",
        imageUrl: "images/cats/nacho.webp",
        id: "0007"
    },
    {
        name: "Caesar",
        gender: "Male",
        age: "Adult",
        size: "Extra Large",
        color: "White / Black",
        characteristics: ["Hungry", "Food Motivated", "Cranky", "Loves Head Pats", "Angry", "Eats dogs"],
        houseTrained: "Yes",
        health: "Vaccinations up to date.",
        goodWith: "N/A",
        adoptionFee: "$100.00",
        imageUrl: "images/cats/caesar.jpg",
        id: "0008"
    },
    {
        name: "Bean",
        gender: "Female",
        age: "Adult",
        size: "Small",
        color: "Tabby (Brown / White / Black)",
        characteristics: ["Energetic", "Loud", "Zoomies at 3 am"],
        houseTrained: "No",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "Other cats, dogs, children",
        adoptionFee: "$2.00",
        imageUrl: "images/cats/bean.jpg",
        id: "0009"
    },
    {
        name: "Atomic Toaster",
        gender: "Female",
        age: "Adult",
        size: "Large",
        color: "Siamese (White / Black / Brown",
        characteristics: ["Friendly", "Affectionate", "Gentle", "Playful", "Smart", "Brave", "Curious", "Funny", "Athletic", "Loves Kisses", "Brave"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "Children",
        adoptionFee: "$0.00",
        imageUrl: "images/cats/atomictoaster.webp",
        id: "0010"
    },
    {
        name: "Julie",
        gender: "Female",
        age: "Young",
        size: "Medium",
        color: "Gray / White",
        characteristics: ["Friendly", "Affectionate", "Playful", "Smart", "Brave", "Curious", "Funny", "Athletic", "Loves kisses", "Gentle"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "Other cats, children",
        adoptionFee: "$100.00",
        imageUrl: "images/cats/julie.webp",
        id: "0011"
    },
    {
        name: "Freckle",
        gender: "Female",
        age: "Senior",
        size: "Large",
        color: "Gold / White",
        characteristics: ["Gentle", "Playful", "Smart", "Brave", "Curious", "Funny", "Athletic", "Loves kisses", "Independent"],
        houseTrained: "Yes",
        health: "Spayed / neutered.",
        goodWith: "Dogs",
        adoptionFee: "$120.00",
        imageUrl: "images/cats/freckle.webp",
        id: "0012"
    },
    {
        name: "iPad 4",
        gender: "Male",
        age: "Adult",
        size: "Medium",
        color: "Tuxedo (Black / White)",
        characteristics: ["Smart", "Brave", "Curious", "Funny"],
        houseTrained: "Yes",
        health: "Vaccinations up to date.",
        goodWith: "Other cats",
        adoptionFee: "$274.00",
        imageUrl: "images/cats/ipad4.webp",
        id: "0013"
    },
    {
        name: "Fantastic Beast (Not a Tiger)",
        gender: "Male",
        age: "Adult",
        size: "Extra Large",
        color: "Orange / Black / White",
        characteristics: ["Big", "Not a Tiger", "Hungry"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "Dogs",
        adoptionFee: "$500.00",
        imageUrl: "images/cats/fantasticbeast.webp",
        id: "0014"
    },
    {
        name: "Skull",
        gender: "Male",
        age: "Young",
        size: "Medium",
        color: "Black",
        characteristics: ["Funny", "Loves kisses", "Independent"],
        houseTrained: "No",
        health: "N/A",
        goodWith: "N/A",
        adoptionFee: "$50.00",
        imageUrl: "images/cats/skull.webp",
        id: "0015"
    },
    {
        name: "Itsy-Bitsy-Spider",
        gender: "Female",
        age: "Young",
        size: "Small",
        color: "Black",
        characteristics: ["Gentle", "Playful", "Smart", "Brave", "Curious", "Funny", "Athletic"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "Children, other cats, dogs",
        adoptionFee: "$90.00",
        imageUrl: "images/cats/itsybitsyspider.webp",
        id: "0016"
    },
    {
        name: "The Great Catsby",
        gender: "Female",
        age: "Adult",
        size: "Large",
        color: "Orange",
        characteristics: ["Handsome", "Fancy", "Gentle", "Might drink your wine", "Prefers to be adopted with Gentleman"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "N/A",
        adoptionFee: "$75.00",
        imageUrl: "images/cats/thegreatcatsby.webp",
        id: "0017"
    },
    {
        name: "Gentleman (The Great Catsby's Son)",
        gender: "Male",
        age: "Young",
        size: "Medium",
        color: "White / Orange",
        characteristics: ["Handsome", "Fancy", "Gentle", "Might eat your blue cheese", "Prefers to be adopted with The Great Catsby"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "Other cats.",
        adoptionFee: "$75.00",
        imageUrl: "images/cats/catsbyson.webp",
        id: "0018"
    },
    {
        name: "Cloud",
        gender: "Male",
        age: "Adult",
        size: "Medium",
        color: "Snow White",
        characteristics: ["Independent", "Protective"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "Children, dogs",
        adoptionFee: "$50.00",
        imageUrl: "images/cats/tom.webp",
        id: "0019"
    },
    {
        name: "BrightHeart",
        gender: "Female",
        age: "Adult",
        size: "Medium",
        color: "Orange / White",
        characteristics: ["Brave", "Protective", "Strong", "Independent"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "Other cats",
        adoptionFee: "$75.00",
        imageUrl: "images/cats/brightheart.webp",
        id: "0020"
    },
    {
        name: "Majesty",
        gender: "Female",
        age: "Adult",
        size: "Medium",
        color: "Orange",
        characteristics: ["Majestic", "Fancy", "Caring", "Quiet"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "Other cats, children, dogs",
        adoptionFee: "$90.00",
        imageUrl: "images/cats/majesty.webp",
        id: "0021"
    },
    {
        name: "Purdy",
        gender: "Male",
        age: "Adult",
        size: "Medium",
        color: "Tabby (Brown / White / Black)",
        characteristics: ["Friendly", "Loves", "Affectionate", "Gentle", "Quiet"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "Dogs",
        adoptionFee: "$75.00",
        imageUrl: "images/cats/purdy.webp",
        id: "0022"
    },
    {
        name: "Danger Dave",
        gender: "Male",
        age: "Adult",
        size: "Large",
        color: "Black / White",
        characteristics: ["Quiet", "Affectionate", "Shy Initially", "Loud Purr", "Gentle"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "N/A",
        adoptionFee: "$75.00",
        imageUrl: "images/cats/dangerdave.webp",
        id: "0023"
    }
]

export const dogs = [
    {
        name: "Nimbus",
        gender: "Male",
        age: "Young",
        size: "Medium",
        color: "Black / White",
        characteristics: ["Friendly", "Adventerous", "Funny"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "Other dogs, children",
        adoptionFee: "$175.00",
        imageUrl: "images/dogs/nimbus.webp",
        id: "0024"
    },
    {
        name: "Nana",
        gender: "female",
        age: "Senior",
        size: "Extra Large",
        color: "Black",
        characteristics: ["Shy", "Friendly", "Playful", "Affectionate", "Big Bear", "Protective", "Elegant"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "Other dogs, children, cats.",
        adoptionFee: "$350.00",
        imageUrl: "images/dogs/nana.webp",
        id: "0025"
    },
    {
        name: "Crayon",
        gender: "Female",
        age: "Adult",
        size: "Small",
        color: "Orange / White",
        characteristics: ["Affectionate", "Curious", "Friendly", "Playful"],
        houseTrained: "Yes",
        health: "Vaccinations up to date",
        goodWith: "N/A",
        adoptionFee: "$350.00",
        imageUrl: "images/dogs/crayon.webp",
        id: "0026"
    },
    {
        name: "Linguini",
        gender: "Male",
        age: "Adult",
        size: "Extra Large",
        color: "Black / Brown",
        characteristics: ["Friendly", "Affectionate", "Curious", "Playful", "Funny"],
        houseTrained: "No",
        health: "N/A",
        goodWith: "Other dogs, cats",
        adoptionFee: "$175.00",
        imageUrl: "images/dogs/linguini.webp",
        id: "0027"
    },
    {
        name: "Fungus",
        gender: "Male",
        age: "Adult",
        size: "Small",
        color: "Gold",
        characteristics: ["Loud", "Protective", "Energetic"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "Cats",
        adoptionFee: "$300.00",
        imageUrl: "images/dogs/fungus.webp",
        id: "0028"
    },
    {
        name: "Naughty Wilbur",
        gender: "Male",
        age: "Adult",
        size: "Small",
        color: "Peach",
        characteristics: ["Affectionate", "Curious", "Gentle", "Funny", "Friendly", "Loves", "Playful"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "Other dogs, children, cats",
        adoptionFee: "$500.00",
        imageUrl: "images/dogs/naughtywilbur.webp",
        id: "0029"
    },
    {
        name: "Poppy",
        gender: "Female",
        age: "Adult",
        size: "Small",
        color: "Black / Brown",
        characteristics: ["Friendly", "Affectionate", "Curious", "Playful", "Funny"],
        houseTrained: "Yes",
        health: "Spayed / neutered.",
        goodWith: "Cats",
        adoptionFee: "$450.00",
        imageUrl: "images/dogs/poppy.webp",
        id: "0030"
    },
    {
        name: "Mickey",
        gender: "Male",
        age: "Puppy",
        size: "Small",
        color: "Black / Brown",
        characteristics: ["Crazy", "Dumb as Bricks", "Ugly-Cute", "Will eat your clothes"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "Other dogs, children, Bean",
        adoptionFee: "$500.00",
        imageUrl: "images/dogs/mickey.webp",
        id: "0031"
    },
    {
        name: "Thickin Nugget",
        gender: "Male",
        age: "Senior",
        size: "Extra Large",
        color: "Gold",
        characteristics: ["Lazy", "Loyal", "Marshmallow"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "Children",
        adoptionFee: "$95.00",
        imageUrl: "images/dogs/thickinnugget.webp",
        id: "0032"
    },
    {
        name: "Ceoul",
        gender: "Male",
        age: "Adult",
        size: "Large",
        color: "Gold",
        characteristics: ["Friendly", "Affectionate", "Gentle", "Playful", "Smart", "Brave", "Curious"],
        houseTrained: "No",
        health: "N/A",
        goodWith: "Children, other dogs, cats",
        adoptionFee: "$120.00",
        imageUrl: "images/dogs/ceoul.webp",
        id: "0033"
    },
    {
        name: "Jim",
        gender: "Male",
        age: "Adult",
        size: "Large",
        color: "Black / Brown",
        characteristics: ["Smart", "Curious", "Independent"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "N/A",
        adoptionFee: "$200.00",
        imageUrl: "images/dogs/jim.webp",
        id: "0034"
    },
    {
        name: "Danger Dane",
        gender: "Male",
        age: "Adult",
        size: "Large",
        color: "Spotted (Gray / White / Black / Brown)",
        characteristics: ["Smart", "Curious", "Independent"],
        houseTrained: "Yes",
        health: "Spayed / neutered.",
        goodWith: "Children, cats",
        adoptionFee: "$150.00",
        imageUrl: "images/dogs/dangerdane.webp",
        id: "0035"
    },
    {
        name: "Rotwood",
        gender: "Female",
        age: "Puppy",
        size: "Small",
        color: "Gray / Black / White",
        characteristics: ["Affectionate", "Curious", "Friendly", "Funny", "Loves"],
        houseTrained: "No",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "Children, cats, other dogs",
        adoptionFee: "$450.00",
        imageUrl: "images/dogs/rotwood.webp",
        id: "0036"
    },
    {
        name: "Bob",
        gender: "Male",
        age: "Puppy",
        size: "Small",
        color: "Black / White",
        characteristics: ["Affectionate", "Dignified", "Friendly", "Gentle", "Independent"],
        houseTrained: "No",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "Children, cats, other dogs",
        adoptionFee: "$120.00",
        imageUrl: "images/dogs/bob.webp",
        id: "0037"
    },
    {
        name: "Lazy Bones",
        gender: "Female",
        age: "Adult",
        size: "Medium",
        color: "Black / White",
        characteristics: ["Athletic", "Not lazy", "likes water"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "Children",
        adoptionFee: "$300.00",
        imageUrl: "images/dogs/lazybones.webp",
        id: "0038"
    },
    {
        name: "Vacuum",
        gender: "Female",
        age: "Adult",
        size: "Small",
        color: "Brown / White",
        characteristics: ["Friendly", "Affectionate", "Gentle", "Playful", "Smart", "Brave", "Curious", "Funny", "Athletic", "Loves Kisses", "Brave"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "Cats",
        adoptionFee: "$250.00",
        imageUrl: "images/dogs/vacuum.webp",
        id: "0039"
    },
    {
        name: "Pendant",
        gender: "Female",
        age: "Young",
        size: "Small",
        color: "Brown / White / Black",
        characteristics: ["Smart", "Brave", "Curious", "Funny", "Athletic", "Loves Kisses", "Brave"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "Other dogs, cats",
        adoptionFee: "$55.00",
        imageUrl: "images/dogs/pendant.webp",
        id: "0040"
    },
    {
        name: "Lily",
        gender: "Female",
        age: "Young",
        size: "Small",
        color: "Brown / White",
        characteristics: ["Loyal", "Protective", "Independent"],
        houseTrained: "Yes",
        health: "Vaccinations up to date",
        goodWith: "Cats",
        adoptionFee: "$140.00",
        imageUrl: "images/dogs/lily.webp",
        id: "0041"
    },
    {
        name: "Jacob",
        gender: "Male",
        age: "Adult",
        size: "Small",
        color: "Gray / White",
        characteristics: ["Gentle", "Playful", "Smart", "Brave", "Curious", "Funny", "Athletic"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "Other dogs",
        adoptionFee: "$300.00",
        imageUrl: "images/dogs/jacob.webp",
        id: "0042"
    },
    {
        name: "Bulldozer",
        gender: "Female",
        age: "Adult",
        size: "Small",
        color: "Brown / White",
        characteristics: ["Loud", "Your worst nightmare"],
        houseTrained: "No",
        health: "N/A",
        goodWith: "N/A",
        adoptionFee: "$0.00",
        imageUrl: "images/dogs/bulldozer.webp",
        id: "0043"
    },
    {
        name: "Merida",
        gender: "Female",
        age: "Adult",
        size: "Extra Large",
        color: "Brown",
        characteristics: ["Funny", "Athletic", "Energetic", "Friendly"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "Other dogs, children",
        adoptionFee: "$500.00",
        imageUrl: "images/dogs/merida.webp",
        id: "0044"
    },
    {
        name: "Sweet Tooth",
        gender: "Male",
        age: "Adult",
        size: "Extra Large",
        color: "White",
        characteristics: ["Friendly", "Affectionate", "Gentle", "Curious", "Loyal", "Loves Kisses"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "Other dogs, children, cats",
        adoptionFee: "$370.00",
        imageUrl: "images/dogs/sweettooth.webp",
        id: "0045"
    },
    {
        name: "Droopy",
        gender: "Male",
        age: "Adult",
        size: "Large",
        color: "Brown",
        characteristics: ["Playful", "Protective"],
        houseTrained: "Yes",
        health: "Vaccinations up to date, spayed / neutered.",
        goodWith: "N/A",
        adoptionFee: "$100.00",
        imageUrl: "images/dogs/droopy.webp",
        id: "0046"
    }
]